
#General settings
[general]
	#How often should the server send tps updates to clients
	#Default is 100 ticks
	#Range: 1 ~ 6000
	refreshTicks = 100
	#Only ops can see tps information, this is to stop tps hunters
	opOnlyMode = false

